name: Build Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build-test:
    name: Test Build Process
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Install global dependencies
        run: |
          npm install -g cross-env serve

      - name: Install project dependencies
        run: yarn install --frozen-lockfile

      - name: Test build process
        run: yarn test:build

      - name: Build web application
        run: yarn build:web

      - name: Build extension
        run: yarn build:ext

      - name: Check build outputs
        run: |
          echo "Checking web build output..."
          ls -la apps/web/web-build/
          
          echo "Checking extension build output..."
          ls -la apps/ext/dist/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-outputs
          path: |
            apps/web/web-build/
            apps/ext/dist/
          retention-days: 7 